"""
core/eln_exporter.py — Export protocols to ELN-compatible formats.
Supports: CSV, Excel (via pandas), JSON-LD.
No openpyxl required — uses pandas which is already installed.
"""
from __future__ import annotations
import csv, io, json
from datetime import datetime


def export_csv(protocol: dict) -> str:
    """Export protocol steps as CSV string."""
    buf = io.StringIO()
    w   = csv.writer(buf)
    w.writerow(["Step", "Instruction", "Volume_uL", "Temp_C",
                "Duration_s", "Citations", "Safety_Note"])
    for s in protocol.get("steps", []):
        w.writerow([
            s.get("step_number", ""),
            s.get("instruction", ""),
            s.get("volume_ul", ""),
            s.get("temperature_celsius", ""),
            s.get("duration_seconds", ""),
            "; ".join(s.get("citations", [])),
            s.get("safety_note", "") or "",
        ])
    return buf.getvalue()


def export_excel(protocol: dict) -> bytes:
    """
    Export protocol as Excel workbook using pandas (no openpyxl needed directly).
    pandas uses openpyxl internally — if not available, falls back to CSV bytes.
    """
    import pandas as pd

    now   = datetime.now().strftime("%Y-%m-%d %H:%M")
    pid   = protocol.get("protocol_id", "")[:8]
    title = protocol.get("title", "Protocol")

    # Build DataFrames
    steps_df = pd.DataFrame([
        {
            "Step":         s.get("step_number", ""),
            "Instruction":  s.get("instruction", ""),
            "Volume (µL)":  s.get("volume_ul", ""),
            "Temp (°C)":    s.get("temperature_celsius", ""),
            "Duration (s)": s.get("duration_seconds", ""),
            "Citations":    "; ".join(s.get("citations", [])),
            "Safety Note":  s.get("safety_note", "") or "",
        }
        for s in protocol.get("steps", [])
    ])

    reagents_df = pd.DataFrame({
        "Reagents":  protocol.get("reagents", []),
    })

    equipment_df = pd.DataFrame({
        "Equipment": protocol.get("equipment", []),
    })

    sources_df = pd.DataFrame([
        {
            "Source ID":  src.get("source_id", ""),
            "Filename":   src.get("filename", ""),
            "Section":    src.get("section", ""),
            "Page":       src.get("page_start", ""),
            "Relevance":  f"{src.get('score', 0):.0%}",
        }
        for src in protocol.get("sources_used", [])
    ])

    summary_df = pd.DataFrame([
        {"Field": "Protocol ID",    "Value": pid},
        {"Field": "Title",          "Value": title},
        {"Field": "Description",    "Value": protocol.get("description", "")},
        {"Field": "Safety Level",   "Value": protocol.get("safety_level", "safe").upper()},
        {"Field": "Confidence",     "Value": f"{protocol.get('confidence_score', 0):.0%}"},
        {"Field": "Steps",          "Value": str(len(protocol.get("steps", [])))},
        {"Field": "Model Used",     "Value": protocol.get("model_used", "")},
        {"Field": "Generated",      "Value": now},
        {"Field": "Generated By",   "Value": "AuroLab v2.0"},
    ])

    buf = io.BytesIO()
    try:
        with pd.ExcelWriter(buf, engine="openpyxl") as writer:
            summary_df.to_excel(writer,   sheet_name="Summary",            index=False)
            steps_df.to_excel(writer,     sheet_name="Protocol Steps",     index=False)
            reagents_df.to_excel(writer,  sheet_name="Reagents & Equipment",index=False)
            if not sources_df.empty:
                sources_df.to_excel(writer, sheet_name="Sources",          index=False)
    except ImportError:
        # openpyxl not installed — return CSV as bytes fallback
        return export_csv(protocol).encode("utf-8")

    buf.seek(0)
    return buf.read()


def export_jsonld(protocol: dict) -> str:
    """Export as JSON-LD for semantic web / ELN integration (Bioschemas)."""
    now = datetime.now().isoformat()
    doc = {
        "@context": {
            "schema":      "https://schema.org/",
            "bioschemas":  "https://bioschemas.org/",
            "aurolab":     "https://aurolab.ai/ontology/",
        },
        "@type":  "bioschemas:LabProtocol",
        "@id":    f"aurolab:protocol/{protocol.get('protocol_id', '')}",
        "schema:name":        protocol.get("title", ""),
        "schema:description": protocol.get("description", ""),
        "schema:dateCreated": now,
        "schema:softwareAgent": "AuroLab v2.0",
        "aurolab:safetyLevel":    protocol.get("safety_level", "safe"),
        "aurolab:confidenceScore":protocol.get("confidence_score", 0),
        "bioschemas:reagent": [
            {"@type": "bioschemas:BioChemEntity", "schema:name": r}
            for r in protocol.get("reagents", [])
        ],
        "bioschemas:instrument": [
            {"@type": "schema:Thing", "schema:name": e}
            for e in protocol.get("equipment", [])
        ],
        "bioschemas:step": [
            {
                "@type":                    "bioschemas:LabProtocolStep",
                "schema:position":          s.get("step_number"),
                "schema:text":              s.get("instruction", ""),
                "aurolab:volumeUL":         s.get("volume_ul"),
                "aurolab:temperatureCelsius":s.get("temperature_celsius"),
                "aurolab:durationSeconds":  s.get("duration_seconds"),
                "aurolab:citations":        s.get("citations", []),
            }
            for s in protocol.get("steps", [])
        ],
    }
    return json.dumps(doc, indent=2, ensure_ascii=False)